algoritmo "semnome"
// Função :
// Autor :
// Data : 15/02/2022
// Seção de Declarações 
var
contador, valor, salto: Inteiro
inicio
// Seção de Comandos
contador <- 0
escreva("Quer contar até quanto? ")
leia(valor)
escreva("Qual será o valor do salto? ")
leia(salto)
enquanto (contador <= valor) faca
         escreval(contador)
         contador <- contador + salto
fimenquanto
escreval("Fim da contagem!")
fimalgoritmo
