algoritmo "semnome"
// Função :
// Autor :
// Data : 08/02/2022
// Seção de Declarações 
var
   x, y, z: Inteiro
inicio
// Seção de Comandos 
   Escreva("Ano Atual (yyyy): ")
   Leia(x)
   Escreva("Ano de Nascimento (yyyy): ")
   Leia(y)
   z <- x-y
   Escreval("IDADE:",Z," ANOS")
   Se z >= 18 entao
      Escreva("APTO A TIRAR A CARTEIRA")
   senao
      Escreva("INAPTO A TIRAR A CARTEIRA")
   FimSE
fimalgoritmo
