algoritmo "Par ou Ímpar"
// Função : Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
// ÍMPAR.
// Autor :
// Data : 10/02/2022
// Seção de Declarações 
var
   n: Inteiro
inicio
// Seção de Comandos 
   Escreva("Digite um número inteiro: ")
   Leia(n)
   Se (n%2 = 0) entao
      Escreval("O número",n," é PAR")
   Senao
        Escreval("O número",n," é ÍMPAR")
   FimSe
fimalgoritmo
