algoritmo "semnome"
// Função :
// Autor :
// Data : 10/02/2022
// Seção de Declarações 
var
   a, b: Inteiro
inicio
// Seção de Comandos 
escreva("Digite o primeiro número inteiro: ")
leia(a)
escreva("Digite o segundo número inteiro: ")
leia(b)
se (a > b) entao
   escreval("O primeiro valor é o maior")
senao
     se (b > a) entao
     escreval("O segundo valor é o maior")
     senao
          escreval("Não existe valor maior, os dois são iguais")
     fimse
fimse
fimalgoritmo
